package com.titlezwc.moment;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP_INFO".
 */
public class AppInfo {

    private String PackageName;
    private Long id;
    private String AppName;
    private String versionName;
    private Integer versionCode;
    private Integer versionCodeUpdate;
    private Integer VisitTimes;
    private Long UseTime;
    private java.util.Date date;

    public AppInfo() {
    }

    public AppInfo(Long id) {
        this.id = id;
    }

    public AppInfo(String PackageName, Long id, String AppName, String versionName, Integer versionCode, Integer versionCodeUpdate, Integer VisitTimes, Long UseTime, java.util.Date date) {
        this.PackageName = PackageName;
        this.id = id;
        this.AppName = AppName;
        this.versionName = versionName;
        this.versionCode = versionCode;
        this.versionCodeUpdate = versionCodeUpdate;
        this.VisitTimes = VisitTimes;
        this.UseTime = UseTime;
        this.date = date;
    }

    public String getPackageName() {
        return PackageName;
    }

    public void setPackageName(String PackageName) {
        this.PackageName = PackageName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return AppName;
    }

    public void setAppName(String AppName) {
        this.AppName = AppName;
    }

    public String getVersionName() {
        return versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    public Integer getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(Integer versionCode) {
        this.versionCode = versionCode;
    }

    public Integer getVersionCodeUpdate() {
        return versionCodeUpdate;
    }

    public void setVersionCodeUpdate(Integer versionCodeUpdate) {
        this.versionCodeUpdate = versionCodeUpdate;
    }

    public Integer getVisitTimes() {
        return VisitTimes;
    }

    public void setVisitTimes(Integer VisitTimes) {
        this.VisitTimes = VisitTimes;
    }

    public Long getUseTime() {
        return UseTime;
    }

    public void setUseTime(Long UseTime) {
        this.UseTime = UseTime;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
